name: fyp
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=7_kmp_llvm
  - _python_abi3_support=1.0=hd8ed1ab_2
  - accelerate=1.12.0=pyhcf101f3_0
  - aiofiles=24.1.0=pyhd8ed1ab_1
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py312h27b7581_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alembic=1.17.2=pyhd8ed1ab_0
  - alsa-lib=1.2.15.1=hb03c661_0
  - altair=6.0.0=pyhd8ed1ab_1
  - annotated-doc=0.0.4=pyhcf101f3_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.12.0=pyhcf101f3_0
  - aom=3.9.1=hac33072_0
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - attr=2.5.2=h39aace5_0
  - attrs=25.4.0=pyhcf101f3_1
  - aws-c-auth=0.9.3=hef928c7_0
  - aws-c-cal=0.9.13=h2c9d079_1
  - aws-c-common=0.12.6=hb03c661_0
  - aws-c-compression=0.3.1=h8b1a151_9
  - aws-c-event-stream=0.5.7=h28f887f_1
  - aws-c-http=0.10.7=ha8fc4e3_5
  - aws-c-io=0.23.3=hdaf4b65_5
  - aws-c-mqtt=0.13.3=hc63082f_11
  - aws-c-s3=0.11.3=h06ab39a_1
  - aws-c-sdkutils=0.2.4=h8b1a151_4
  - aws-checksums=0.2.7=h8b1a151_5
  - aws-crt-cpp=0.35.4=h8824e59_0
  - aws-sdk-cpp=1.11.606=h20b40b1_10
  - azure-core-cpp=1.16.1=h3a458e0_0
  - azure-identity-cpp=1.13.2=h3a5f585_1
  - azure-storage-blobs-cpp=12.15.0=h2a74896_1
  - azure-storage-common-cpp=12.11.0=h3d7a050_1
  - azure-storage-files-datalake-cpp=12.13.0=hf38f1be_1
  - backports.zstd=1.2.0=py312h90b7ffd_0
  - binaryornot=0.4.4=pyhd8ed1ab_2
  - binutils_impl_linux-64=2.45=default_hfdba357_105
  - binutils_linux-64=2.45=default_h4852527_105
  - bitsandbytes=0.49.0=cuda129_py312h69cc2ad_200
  - blinker=1.9.0=pyhff2d567_0
  - bottle=0.13.4=pyhe01879c_0
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - brotli-python=1.2.0=py312hdb49522_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cachetools=6.2.4=pyhd8ed1ab_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - chardet=5.2.0=pyhd8ed1ab_3
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - colorlog=6.10.1=pyh707e725_0
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py312hd9148b4_3
  - cookiecutter=2.6.0=pyhd8ed1ab_1
  - cpython=3.12.12=py312hd8ed1ab_1
  - cuda-cccl_linux-64=12.9.27=ha770c72_0
  - cuda-crt-dev_linux-64=12.9.86=ha770c72_2
  - cuda-crt-tools=12.9.86=ha770c72_2
  - cuda-cudart=12.9.79=h5888daf_0
  - cuda-cudart-dev=12.9.79=h5888daf_0
  - cuda-cudart-dev_linux-64=12.9.79=h3f2d84a_0
  - cuda-cudart-static=12.9.79=h5888daf_0
  - cuda-cudart-static_linux-64=12.9.79=h3f2d84a_0
  - cuda-cudart_linux-64=12.9.79=h3f2d84a_0
  - cuda-cuobjdump=12.9.82=hffce074_1
  - cuda-cupti=12.9.79=h676940d_1
  - cuda-driver-dev=12.9.79=h5888daf_0
  - cuda-driver-dev_linux-64=12.9.79=h3f2d84a_0
  - cuda-nvcc-dev_linux-64=12.9.86=he91c749_2
  - cuda-nvcc-impl=12.9.86=h85509e4_2
  - cuda-nvcc-tools=12.9.86=he02047a_2
  - cuda-nvcc_linux-64=12.9.86=he0b4e1d_4
  - cuda-nvdisasm=12.9.88=hffce074_1
  - cuda-nvrtc=12.9.86=hecca717_1
  - cuda-nvtx=12.9.79=hecca717_1
  - cuda-nvvm-dev_linux-64=12.9.86=ha770c72_2
  - cuda-nvvm-impl=12.9.86=h4bc722e_2
  - cuda-nvvm-tools=12.9.86=h4bc722e_2
  - cuda-version=12.9=h4f385c5_3
  - cudnn=9.10.2.21=hbcb9cd8_0
  - cut_cross_entropy=25.1.1=pyhd8ed1ab_0
  - cycler=0.12.1=pyhcf101f3_2
  - cyrus-sasl=2.1.28=hd9c7081_0
  - datasets=4.3.0=pyhcf101f3_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h24cb091_1
  - debugpy=1.8.19=py312h372c3de_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - diffusers=0.35.2=pyhd8ed1ab_0
  - dill=0.4.0=pyhcf101f3_1
  - dnspython=2.8.0=pyhcf101f3_0
  - docstring_parser=0.17.0=pyhd8ed1ab_0
  - double-conversion=3.4.0=hecca717_0
  - einops=0.8.1=pyhd8ed1ab_0
  - email-validator=2.3.0=pyhd8ed1ab_0
  - email_validator=2.3.0=hd8ed1ab_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - eval_type_backport=0.3.1=pyha770c72_0
  - evaluate=0.4.6=pyhcf101f3_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fastapi=0.127.0=hdf53b3f_0
  - fastapi-cli=0.0.20=pyhcf101f3_0
  - fastapi-core=0.127.0=pyhcf101f3_0
  - ffmpeg=8.0.1=gpl_hf567e27_908
  - ffmpy=0.3.0=pyhb6f538c_0
  - filelock=3.20.1=pyhd8ed1ab_0
  - flash-attn=2.8.3=py312h66cfc6a_1
  - fmt=12.0.0=h2b0788b_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py312h8a5da7c_0
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - frozenlist=1.7.0=py312h447239a_0
  - fsspec=2025.9.0=pyhd8ed1ab_0
  - gcc_impl_linux-64=14.3.0=he8b2097_16
  - gcc_linux-64=14.3.0=h298d278_17
  - gdk-pixbuf=2.44.4=h2b0a6b4_0
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=hd590300_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.46=pyhd8ed1ab_0
  - glog=0.7.1=hbabe93e_0
  - glslang=16.1.0=hfd11570_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py312hcaba1f9_2
  - gradio=5.49.1=pyhd8ed1ab_0
  - gradio-client=1.13.3=pyhd8ed1ab_0
  - graphite2=1.3.14=hecca717_2
  - greenlet=3.3.0=py312h1289d80_0
  - groovy-python=0.1.2=pyhd8ed1ab_0
  - gxx_impl_linux-64=14.3.0=h2185e75_16
  - gxx_linux-64=14.3.0=h310e576_17
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.2.0=h15599e2_0
  - hf-transfer=0.1.9=py312h914ccca_2
  - hf-xet=1.2.1=py310hb823017_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httptools=0.7.1=py312h4c3975b_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - huggingface_hub=0.36.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - intel-gmmlib=22.9.0=hb700be7_0
  - intel-media-driver=25.3.4=hecca717_0
  - ipykernel=7.1.0=pyha191276_0
  - ipython=9.8.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - kernel-headers_linux-64=6.12.0=he073ed8_5
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py312h0a2e395_2
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - lerc=4.0.0=h0aef613_1
  - level-zero=1.26.3=hb700be7_0
  - libabseil=20250512.1=cxx17_hba17884_0
  - libarrow=22.0.0=hb6ed5f4_6_cpu
  - libarrow-acero=22.0.0=h635bf11_6_cpu
  - libarrow-compute=22.0.0=h8c2c5c3_6_cpu
  - libarrow-dataset=22.0.0=h635bf11_6_cpu
  - libarrow-substrait=22.0.0=h3f74fd7_6_cpu
  - libass=0.17.4=h96ad9f0_0
  - libavif16=1.3.0=h6395336_2
  - libblas=3.11.0=5_h5875eb1_mkl
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcap=2.77=h3ff7636_0
  - libcblas=3.11.0=5_hfef963f_mkl
  - libclang-cpp21.1=21.1.7=default_h99862b1_2
  - libclang13=21.1.7=default_h746c552_2
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=12.9.1.4=h676940d_1
  - libcudnn=9.10.2.21=hf7e9902_0
  - libcudnn-dev=9.10.2.21=h58dd1b1_0
  - libcudss=0.7.1.4=h58dd1b1_0
  - libcufft=11.4.1.4=hecca717_1
  - libcufile=1.14.1.1=hbc026e6_1
  - libcups=2.3.3=hb8b1518_5
  - libcurand=10.3.10.19=h676940d_1
  - libcurl=8.17.0=h4e3cde8_1
  - libcusolver=11.7.5.82=h676940d_2
  - libcusparse=12.5.10.65=hecca717_2
  - libde265=1.0.15=h00ab1b0_0
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libflac=1.5.0=he200343_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-devel_linux-64=14.3.0=hf649bbc_116
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.3=h6548e54_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=he0feb66_16
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - libgrpc=1.73.1=h3288cfb_1
  - libheif=1.19.7=gpl_hc18d805_100
  - libhwloc=2.12.1=default_hafda6a7_1003
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=5_h5e43f62_mkl
  - libllvm21=21.1.8=hf7376ad_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libmagma=2.9.0=ha7672b3_5
  - libnghttp2=1.67.0=had1ee68_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libnvjitlink=12.9.86=hecca717_2
  - libnvjpeg=12.4.0.76=hecca717_1
  - libnvptxcompiler-dev=12.9.86=ha770c72_2
  - libnvptxcompiler-dev_linux-64=12.9.86=ha770c72_2
  - libogg=1.3.5=hd0c01bc_1
  - libopengl=1.7.0=ha4b6fd6_2
  - libopentelemetry-cpp=1.21.0=hb9b0907_1
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_1
  - libopenvino=2025.4.1=hb56ce9e_0
  - libopenvino-auto-batch-plugin=2025.4.1=hd85de46_0
  - libopenvino-auto-plugin=2025.4.1=hd85de46_0
  - libopenvino-hetero-plugin=2025.4.1=hd41364c_0
  - libopenvino-intel-cpu-plugin=2025.4.1=hb56ce9e_0
  - libopenvino-intel-gpu-plugin=2025.4.1=hb56ce9e_0
  - libopenvino-intel-npu-plugin=2025.4.1=hb56ce9e_0
  - libopenvino-ir-frontend=2025.4.1=hd41364c_0
  - libopenvino-onnx-frontend=2025.4.1=h1862bb8_0
  - libopenvino-paddle-frontend=2025.4.1=h1862bb8_0
  - libopenvino-pytorch-frontend=2025.4.1=hecca717_0
  - libopenvino-tensorflow-frontend=2025.4.1=h0767aad_0
  - libopenvino-tensorflow-lite-frontend=2025.4.1=hecca717_0
  - libopus=1.6=h0fd0de7_0
  - libparquet=22.0.0=h7376487_6_cpu
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.53=h421ea60_0
  - libpq=18.1=h5c52fec_2
  - libprotobuf=6.31.1=h49aed37_4
  - libre2-11=2025.11.05=h7b12aa8_0
  - librsvg=2.60.0=h61e6d4b_0
  - libsanitizer=14.3.0=h8f1669f_16
  - libsentencepiece=0.2.1=h1d72405_1
  - libsndfile=1.2.2=hc7d488a_2
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.51.1=h0c1763c_1
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-devel_linux-64=14.3.0=h9f08a49_116
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libsystemd0=258.3=h6569c3e_0
  - libthrift=0.22.0=h454ac66_1
  - libtiff=4.7.1=h9d88235_1
  - libtorch=2.8.0=cuda129_mkl_hf53477d_302
  - libudev1=258.3=h6569c3e_0
  - libunwind=1.8.3=h65a8314_0
  - liburing=2.12=hb700be7_0
  - libusb=1.0.29=h73b1eb8_0
  - libutf8proc=2.11.2=hfe17d71_0
  - libuuid=2.41.3=h5347b49_0
  - libuv=1.51.0=hb03c661_1
  - libva=2.23.0=he1eb515_0
  - libvorbis=1.3.7=h54a6638_2
  - libvpl=2.15.0=h54a6638_1
  - libvpx=1.15.2=hecca717_0
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxgboost=3.1.2=cuda129_h54c741a_2
  - libxkbcommon=1.13.1=hca5e8e5_0
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libxslt=1.1.43=h711ed8c_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=21.1.8=h4922eb0_0
  - lz4-c=1.10.0=h5888daf_1
  - mako=1.3.10=pyhcf101f3_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py312h8a5da7c_0
  - matplotlib=3.10.8=py312h7900ff3_0
  - matplotlib-base=3.10.8=py312he3d6523_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mistral-common=1.8.8=pyhc455866_0
  - mkl=2025.3.0=h0e700b2_462
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpg123=1.32.9=hc50e24c_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgspec=0.20.0=py312h4c3975b_1
  - multidict=6.7.0=py312h8a5da7c_0
  - multiprocess=0.70.16=py312h5253ce2_2
  - munkres=1.1.4=pyhd8ed1ab_1
  - mypy_extensions=1.1.0=pyha770c72_0
  - narwhals=2.14.0=pyhcf101f3_0
  - nccl=2.29.2.1=h4d09622_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.6.1=pyhcf101f3_0
  - nlohmann_json=3.12.0=h54a6638_1
  - nltk=3.9.2=pyhcf101f3_1
  - nodejs=24.12.0=h36edbcc_0
  - numpy=2.4.0=py312h33ff503_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.6.0=hc22cd8d_0
  - openjpeg=2.5.4=h55fea9a_0
  - openldap=2.6.10=he970967_0
  - openpyxl=3.1.5=py312h7f6eeab_2
  - openssl=3.6.0=h26f9b46_0
  - optree=0.18.0=py312hd9148b4_0
  - optuna=4.6.0=pyhd8ed1ab_0
  - optuna-dashboard=0.20.0=pyhd8ed1ab_0
  - optuna-integration=4.6.0=pyhd8ed1ab_0
  - orc=2.2.1=hd747db4_0
  - orjson=3.11.5=py312h94568fe_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py312hf79963d_1
  - pango=1.56.4=hadf4263_0
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.47=haa7fec5_0
  - peft=0.18.0=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pillow=11.3.0=py312h7b42cdd_3
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - platformdirs=4.5.1=pyhcf101f3_0
  - playwright=1.57.0=h5585027_0
  - playwright-python=1.57.0=pyhcf101f3_0
  - plotly=6.5.0=pyhd8ed1ab_0
  - pluggy=1.6.0=pyhf9edf01_1
  - prometheus-cpp=1.3.0=ha5d0236_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=py312h178313f_0
  - protobuf=6.31.1=py312hb8af0ac_2
  - psutil=7.2.0=py312h5253ce2_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pugixml=1.15=h3f63f65_0
  - pulseaudio-client=17.0=h9a6aba3_3
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-xgboost=3.1.2=cuda129_pyh3031c10_2
  - pyarrow=22.0.0=py312h7900ff3_0
  - pyarrow-core=22.0.0=py312hc195796_0_cpu
  - pybind11=2.13.6=pyhc790b64_3
  - pybind11-abi=4=hd8ed1ab_3
  - pybind11-global=2.13.6=pyh217bc35_3
  - pycountry=24.6.1=pyhd8ed1ab_0
  - pydantic=2.11.10=pyh3cfb1c2_0
  - pydantic-core=2.33.2=py312h680f630_0
  - pydantic-extra-types=2.10.6=pyh3cfb1c2_0
  - pydantic-settings=2.12.0=pyh3cfb1c2_0
  - pydeck=0.9.1=pyhd8ed1ab_0
  - pydub=0.25.1=pyhd8ed1ab_1
  - pyee=13.0.0=pyhd8ed1ab_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.3.1=pyhcf101f3_0
  - pyre-extensions=0.0.32=pyhd8ed1ab_1
  - pyside6=6.10.1=py312h9da60e5_0
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=9.0.2=pyhcf101f3_0
  - pytest-base-url=2.1.0=pyhd8ed1ab_1
  - pytest-playwright=0.7.2=pyhd8ed1ab_1
  - python=3.12.12=hd63d673_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-gil=3.12.12=hd8ed1ab_1
  - python-multipart=0.0.21=pyh332efcf_0
  - python-slugify=8.0.4=pyhd8ed1ab_1
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python-xxhash=3.6.0=py312h0d868a3_1
  - python_abi=3.12=8_cp312
  - pytorch=2.8.0=cuda129_mkl_py312_had1c889_302
  - pytorch-gpu=2.8.0=cuda129_mkl_h43a4b0b_302
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py312h8a5da7c_0
  - pyzmq=27.1.0=py312hfb55c3c_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.10.1=h6f76662_3
  - rav1e=0.7.1=h8fae777_3
  - rdma-core=60.0=hecca717_0
  - re2=2025.11.05=h5301d42_0
  - readline=8.3=h853b02a_0
  - referencing=0.37.0=pyhcf101f3_0
  - regex=2025.11.3=py312h4c3975b_1
  - requests=2.32.5=pyhd8ed1ab_0
  - rich=14.2.0=pyhcf101f3_0
  - rich-toolkit=0.17.1=pyhcf101f3_0
  - rpds-py=0.30.0=py312h868fb18_0
  - ruff=0.14.10=h4196e79_0
  - s2n=1.6.2=he8a4886_1
  - safehttpx=0.1.7=pyhd8ed1ab_0
  - safetensors=0.7.0=py312h0ccc70a_0
  - scikit-learn=1.8.0=np2py312h3226591_1
  - scipy=1.16.3=py312h54fa4ab_2
  - sdl2=2.32.56=h54a6638_0
  - sdl3=3.2.28=h3b84278_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - semantic_version=2.10.0=pyhd8ed1ab_0
  - sentencepiece=0.2.1=h074af39_1
  - sentencepiece-python=0.2.1=py312h64fda98_1
  - sentencepiece-spm=0.2.1=h1d72405_1
  - setuptools=80.9.0=pyhff2d567_0
  - shaderc=2025.5=h3e344bc_0
  - shellingham=1.5.4=pyhd8ed1ab_2
  - shtab=1.8.0=pyhd8ed1ab_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=ha0421bc_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.2=h03e3b7b_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - spirv-tools=2025.4=hb700be7_0
  - sqlalchemy=2.0.45=py312h4c3975b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - starlette=0.50.0=pyhfdc7a7d_0
  - statsmodels=0.14.6=py312h4f23490_0
  - streamlit=1.52.2=pyhd8ed1ab_0
  - svt-av1=3.1.2=hecca717_0
  - sympy=1.14.0=pyh2585a3b_105
  - sysroot_linux-64=2.39=hc4b9eeb_5
  - tbb=2022.3.0=h8d10470_1
  - tenacity=9.1.2=pyhd8ed1ab_0
  - text-unidecode=1.3=pyhd8ed1ab_2
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tiktoken=0.12.0=py312hd04cf1f_3
  - tk=8.6.13=noxft_ha0e22de_103
  - tokenizers=0.22.2=py312hf875000_0
  - toml=0.10.2=pyhcf101f3_3
  - tomli=2.3.0=pyhcf101f3_0
  - tomlkit=0.13.3=pyha770c72_0
  - torchao=0.13.0=cuda_129py312hb4f918a_
  - torchvision=0.24.0=cuda129_py312_h9f56bbf_2
  - torchvision-extra-decoders=0.0.2=py312hd347cc9_4
  - tornado=6.5.4=py312h961da02_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - transformers=4.56.2=pyhd8ed1ab_0
  - triton=3.4.0=cuda129py312h811769c_1
  - trl=0.23.0=pyhd8ed1ab_0
  - typeguard=4.4.4=pyhd8ed1ab_0
  - typer=0.20.1=pyhd0b5f5c_0
  - typer-slim=0.20.1=pyhcf101f3_0
  - typer-slim-standard=0.20.1=h058c98f_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_inspect=0.9.0=pyhd8ed1ab_1
  - tyro=1.0.3=pyhd8ed1ab_0
  - tzdata=2025c=h8577fbf_0
  - unicodedata2=17.0.0=py312h4c3975b_1
  - unsloth=2025.12.9=pyhd8ed1ab_0
  - unsloth_zoo=2025.12.7=pyhd8ed1ab_0
  - urllib3=2.6.2=pyhd8ed1ab_0
  - uvicorn=0.40.0=pyhc90fa1f_0
  - uvicorn-standard=0.40.0=h4cd5af1_0
  - uvloop=0.22.1=py312h4c3975b_1
  - watchdog=6.0.0=py312h7900ff3_2
  - watchfiles=1.1.1=py312h0ccc70a_0
  - wayland=1.24.0=hd6090a7_1
  - wayland-protocols=1.47=hd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - websockets=15.0.1=py312h5253ce2_2
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.6=hb03c661_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xformers=0.0.32.post2=cuda_129py312he28d658_0
  - xgboost=3.1.2=cuda129_pyh5c66634_2
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xxhash=0.8.3=hb47aa4a_0
  - yaml=0.2.5=h280c20c_3
  - yarl=1.22.0=py312h8a5da7c_0
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb78ec9c_6
  - pip:
    - apollo-torch==1.0.3
    - st-circular-progress==0.3.9

prefix: "/home/batman/micromamba/envs/fyp"
